"""Tests for :func:`bat.plugins.docs.generate_docs` (CARD-018).

Uses the same on-disk local-plugins-directory + ``ModuleSchema`` fixture
pattern established in ``tests/test_cli_plugins.py`` /
``tests/test_plugins_discovery.py``: write small plugin module files under a
real ``plugins/`` directory, run discovery (CARD-006) against it to build a
real registry, then call ``generate_docs`` directly on that registry.
"""

from __future__ import annotations

import importlib.metadata
import sys
from pathlib import Path

import pytest

from bat.plugins.discovery import discover_plugins
from bat.plugins.docs import generate_docs

READ_MODULE = '''\
from pydantic import BaseModel, Field
from bat.plugins.schema import ModuleSchema, InputField, OutputField


class Schema(ModuleSchema):
    class Meta:
        name = "core.wfdb.read"
        description = "Read a WFDB record from disk."
        citations = "none"

    class Params(BaseModel):
        path: str = Field(..., description="Path to the WFDB record")

    class Inputs(BaseModel):
        pass

    class Outputs(BaseModel):
        signal: OutputField(artifact_type="signal", artifact_format="wfdb")


schema = Schema


def run(inputs, params, context=None):
    return {}
'''

WRITE_MODULE = '''\
from pydantic import BaseModel, Field
from bat.plugins.schema import ModuleSchema, InputField, OutputField


class Schema(ModuleSchema):
    class Meta:
        name = "core.wfdb.write"
        description = "Write a signal artifact to disk in WFDB format."
        citations = "none"

    class Params(BaseModel):
        pass

    class Inputs(BaseModel):
        signal: InputField(artifact_type="signal", artifact_format="wfdb")

    class Outputs(BaseModel):
        pass


schema = Schema


def run(inputs, params, context=None):
    return {}
'''

RPEAKS_MODULE = '''\
from pydantic import BaseModel, Field
from bat.plugins.schema import ModuleSchema, InputField, OutputField


class Schema(ModuleSchema):
    class Meta:
        name = "lab.ecg.detect_rpeaks"
        description = "Detect R-peaks in an ECG signal using the Pan-Tompkins algorithm."
        citations = [
            "Pan J, Tompkins W. A real-time QRS detection algorithm. IEEE TBME. 1985."
        ]
        examples = [
            {
                "id": "detect_rpeaks",
                "name": "Detect R-peaks",
                "module": "lab.ecg.detect_rpeaks",
                "inputs": {"signal": {"artifact": "filtered_signal"}},
                "params": {"min_distance_ms": 200.0},
                "outputs": {"rpeaks": {"type": "annotations", "format": "wfdb"}},
            }
        ]

    class Params(BaseModel):
        min_distance_ms: float = Field(
            default=200.0, description="Minimum distance between peaks in ms"
        )

    class Inputs(BaseModel):
        signal: InputField(artifact_type="signal", artifact_format="wfdb")

    class Outputs(BaseModel):
        rpeaks: OutputField(artifact_type="annotations", artifact_format="wfdb")


schema = Schema


def run(inputs, params, context=None):
    return {}
'''


def _write(base: Path, relpath: str, contents: str) -> Path:
    path = base / relpath
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(contents)
    return path


@pytest.fixture(autouse=True)
def _clean_sys_state():
    """Restore ``sys.path``/``sys.modules`` after every test -- discovery
    imports plugin packages by dotted name into the real module cache; see
    ``tests/test_plugins_discovery.py`` for the full rationale."""
    path_before = list(sys.path)
    modules_before = set(sys.modules)
    yield
    sys.path[:] = path_before
    for name in list(sys.modules):
        if name not in modules_before:
            del sys.modules[name]


@pytest.fixture()
def no_installed_plugins(monkeypatch):
    monkeypatch.setattr(importlib.metadata, "entry_points", lambda **kwargs: [])


@pytest.fixture()
def registry(tmp_path, no_installed_plugins):
    plugins_dir = tmp_path / "plugins"
    _write(plugins_dir, "core/__init__.py", "")
    _write(plugins_dir, "core/wfdb/__init__.py", "")
    _write(plugins_dir, "core/wfdb/read.py", READ_MODULE)
    _write(plugins_dir, "core/wfdb/write.py", WRITE_MODULE)
    _write(plugins_dir, "lab/__init__.py", "")
    _write(plugins_dir, "lab/ecg/__init__.py", "")
    _write(plugins_dir, "lab/ecg/detect_rpeaks.py", RPEAKS_MODULE)
    return discover_plugins(plugins_dir)


def test_output_is_valid_markdown_with_title_and_date(registry):
    output = generate_docs(registry)
    assert output.startswith("# BAT Plugin Reference")
    assert "Generated by `bat plugins docs` on " in output


def test_all_modules_appear_in_output(registry):
    output = generate_docs(registry)
    assert "### `core.wfdb.read`" in output
    assert "### `core.wfdb.write`" in output
    assert "### `lab.ecg.detect_rpeaks`" in output


def test_modules_grouped_by_collection_namespace(registry):
    output = generate_docs(registry)
    assert "## core" in output
    assert "## lab" in output

    core_idx = output.index("## core")
    lab_idx = output.index("## lab")
    read_idx = output.index("### `core.wfdb.read`")
    write_idx = output.index("### `core.wfdb.write`")
    rpeaks_idx = output.index("### `lab.ecg.detect_rpeaks`")

    # Both core modules fall between the "## core" and "## lab" headings.
    assert core_idx < read_idx < lab_idx
    assert core_idx < write_idx < lab_idx
    # lab's module falls after the "## lab" heading.
    assert lab_idx < rpeaks_idx


def test_citations_none_rendered_literally(registry):
    output = generate_docs(registry)
    assert "**Citations:** none" in output


def test_citations_list_rendered_as_bullets(registry):
    output = generate_docs(registry)
    assert "**Citations:**\n- Pan J, Tompkins W." in output


def test_parameter_table_includes_type_required_default_description(registry):
    output = generate_docs(registry)
    # Required param, no default.
    assert "| path" in output
    assert "string" in output
    assert "Path to the WFDB record" in output

    # Optional param with a default.
    assert "min_distance_ms" in output
    assert "200.0" in output
    assert "Minimum distance between peaks in ms" in output


def test_module_with_no_params_or_inputs_renders_none(registry):
    output = generate_docs(registry)
    # core.wfdb.read declares no Inputs.
    read_block = output[output.index("### `core.wfdb.read`") : output.index("### `core.wfdb.write`")]
    assert "#### Inputs\n\n(none)" in read_block

    # core.wfdb.write declares no Params.
    write_block = output[
        output.index("### `core.wfdb.write`") : output.index("### `lab.ecg.detect_rpeaks`")
    ]
    assert "#### Parameters\n\n(none)" in write_block


def test_outputs_table_rendered(registry):
    output = generate_docs(registry)
    assert "#### Outputs" in output
    assert "signal" in output
    assert "wfdb" in output
    assert "annotations" in output


def test_module_with_examples_includes_yaml_block(registry):
    output = generate_docs(registry)
    assert "#### Examples" in output
    assert "```yaml" in output
    assert "- id: detect_rpeaks" in output
    assert "module: lab.ecg.detect_rpeaks" in output


def test_module_without_examples_has_no_examples_section(registry):
    output = generate_docs(registry)
    read_block = output[output.index("### `core.wfdb.read`") : output.index("### `core.wfdb.write`")]
    assert "#### Examples" not in read_block


def test_source_shows_local_for_local_plugins(registry):
    output = generate_docs(registry)
    assert "**Source:** core (local)" in output
    assert "**Source:** lab (local)" in output


def test_empty_registry_still_produces_valid_header():
    output = generate_docs({})
    assert output.startswith("# BAT Plugin Reference")
